set_health:
  fields:
    state:
      required: true
      selector:
        select:
          options:
            - ok
            - error
    timestamp:
      required: false
      example: "2026-09-03T12:00:00+00:00"
      selector:
        text:
    version:
      required: false
      example: "0.1.0"
      selector:
        text:
